[package]
name = "teckhoff/posthogluau"
description = "A Luau implementation of the PostHog-Node library."
version = "0.1.0"
license = "Apache-2.0"
authors = ["Trevor Eckhoff <trevor@trevoreckhoff.com>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[dependencies]
